"""add data_retorno and url_capa

Revision ID: 93a299081891
Revises: c52a297f76ff
Create Date: 2026-06-16 22:45:44.006495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93a299081891"
down_revision: Union[str, None] = "c52a297f76ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("viagem", sa.Column("data_retorno", sa.Date(), nullable=True))
    op.add_column("viagem", sa.Column("url_capa", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("viagem", "url_capa")
    op.drop_column("viagem", "data_retorno")
    # ### end Alembic commands ###
