"""Config Inicial

Revision ID: 9f713a67a088
Revises: None
Create Date: 2026-03-28 22:06:56.459860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f713a67a088'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('apelido', sa.String(length=80), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('LIDER', 'ADMIN', name='tipo_usuario'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('viagem',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao_precos', sa.Text(), nullable=True),
    sa.Column('data_partida', sa.Date(), nullable=False),
    sa.Column('vagas_totais', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'ESGOTADO', name='status_viagem'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_grupo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_viagem', sa.BigInteger(), nullable=False),
    sa.Column('id_lider', sa.BigInteger(), nullable=False),
    sa.Column('qtd_vagas', sa.Integer(), nullable=False),
    sa.Column('valor_acordado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADO', 'BLOQUEADO', 'CONFIRMADO', 'CANCELADO', name='status_reserva'), nullable=False),
    sa.Column('substatus', sa.Enum('AGUARDANDO_CONTATO', 'EM_ATENDIMENTO', 'AGUARDANDO_PIX', name='substatus_reserva'), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_responsavel_id', sa.BigInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_responsavel_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_lider'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_viagem'], ['viagem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_redefinicao_senha',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_redefinicao_senha_token'), 'token_redefinicao_senha', ['token'], unique=True)
    op.create_table('passageiro',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_reserva', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('eh_lider', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva_grupo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passageiro')
    op.drop_index(op.f('ix_token_redefinicao_senha_token'), table_name='token_redefinicao_senha')
    op.drop_table('token_redefinicao_senha')
    op.drop_table('reserva_grupo')
    op.drop_table('viagem')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
